# Generated by Django 4.2 on 2023-05-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='lastName',
            field=models.CharField(help_text='Zadejte příjmení doktora', max_length=45, verbose_name='příjmení'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(help_text='Zadejte jméno doktora', max_length=40, verbose_name='křestní jméno'),
        ),
    ]
