# Generated by Django 4.2 on 2023-05-11 18:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_doctor_lastname_alter_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte množství podání léku za den (1 - 10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('neurologie', 'Neurologie'), ('ortopedie', 'Ortopedie'), ('pediatrie', 'Pediatrie'), ('kardiologie', 'Kardiologie'), ('jiné', 'Jiné')], help_text='Vyberte doktorovu specializaci', max_length=20, verbose_name='Specializace'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, help_text='Zadejte popis léku', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(help_text='Zadejte název léku', max_length=55, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='admission',
            field=models.DateField(default=django.utils.timezone.now, help_text='Zadejte datum přijetí pacienta', verbose_name='Přijetí'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='lastName',
            field=models.CharField(help_text='Zadejte příjmení pacienta', max_length=45, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='name',
            field=models.CharField(help_text='Zadejte křestní jméno pacienta', max_length=40, verbose_name='Křestní jméno'),
        ),
    ]
